blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://forum.camunda.io/c/camunda-platform-8-topics
    about: Head over to our community forum to ask questions and get answers.
