from setuptools import setup

setup(
   name='Camunda',
   version='1.0',
   description='',
   author='',
   author_email='noone@example.com',
   packages=[
      'Camunda',
      'Camunda.Archive',
      'Camunda.Browser.Selenium',
      'Camunda.Calendar',
      'Camunda.Desktop',
      'Camunda.Desktop.Clipboard',
      'Camunda.Desktop.OperatingSystem',
      'Camunda.Excel.Application',
      'Camunda.Excel.Files',
      'Camunda.FileSystem',
      'Camunda.FTP',
      'Camunda.HTTP',
      'Camunda.Images',
      'Camunda.JavaAccessBridge',
      'Camunda.JSON',
      'Camunda.MFA',
      'Camunda.MSGraph',
      'Camunda.Outlook.Application',
      'Camunda.PDF',
      'Camunda.SAP',
      'Camunda.Tables',
      'Camunda.Tasks',
      'Camunda.Windows',
      'Camunda.Word.Application'
      ], 
   install_requires=[
      "rpaframework",
      "rpaframework-pdf",
      "rpaframework-windows"
   ], 
)
